'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WestWood_Classic.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property _93() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("93", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property allied() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("allied", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property am_allied() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("am_allied", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property am_soviet() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("am_soviet", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property C_C95exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("C_C95exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property cclocal_e() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cclocal_e", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property cclocal_g() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cclocal_g", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property cclocal_m() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cclocal_m", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property cclocal_n() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cclocal_n", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property cclocal_v() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cclocal_v", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ccspeecchi() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ccspeecchi", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ccspeecheng() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ccspeecheng", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 [Options]
        '''HardwareFills=0
        '''VideoBackBuffer=1
        '''FreeScrolling=0
        '''AutoScroll=1
        '''SlowPalette=1
        '''ScoreVolume=112
        '''Volume=113
        '''ScrollRate=3
        '''GameSpeed=1
        '''Compatibility=0
        '''DeathAnnounce=No
        '''Socket=0
        '''DestNet=00.00.00.00
        '''SafeScrolling=No
        '''
        '''[Video]
        '''Width=640
        '''Height=400
        '''Brightness=128
        '''Contrast=128
        '''Tint=128
        '''Color=128
        '''VerticalVideoStretch=i  ; [S]canlines, [D]uplicate, [I]nterpolate
        '''StretchAttract=Yes
        '''
        '''[Music]
        '''IsScoreShuffle=0
        '''IsScoreRepeat=0
        '''UseCreditsMusic=Yes
        '''RemixScores=Yes         ; Enable music r [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property conquer() As String
            Get
                Return ResourceManager.GetString("conquer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property cs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property d2k() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("d2k", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ddraw_dll() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ddraw_dll", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 ; cnc-ddraw - https://github.com/CnCNet/cnc-ddraw - https://cncnet.org
        '''
        '''[ddraw]
        '''; ### Optional settings ###
        '''; Use the following settings to adjust the look and feel to your liking
        '''
        '''
        '''; Stretch to custom resolution, 0 = defaults to the size game requests
        '''width=0
        '''height=0
        '''
        '''; Override the width/height settings shown above and always stretch to fullscreen
        '''; Note: Can be combined with &apos;windowed=true&apos; to get windowed-fullscreen aka borderless mode
        '''fullscreen=false
        '''
        '''; Run in windowed mode rather than [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ddraw_ini() As String
            Get
                Return ResourceManager.GetString("ddraw_ini", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property htitle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("htitle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ra95exe() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ra95exe", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property raspeechchi() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("raspeechchi", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 [Options]
        '''ScrollFix=Yes
        '''LimitCpuUsage=Yes
        '''SlowerScrollrate=No
        '''HardwareFills=No
        '''VideoBackBuffer=Yes
        '''Resolution=0
        '''Width=640
        '''Height=400
        '''ShowAllMusic=Yes
        '''PlayEnglishIntro=Yes
        '''VideoInterlaceMode=2
        '''SkipScoreScreen=No
        '''RandomStartingSong=No
        '''GameLanguage=1
        '''Show640x480BlackBars=false
        '''MouseWheelScrolling=Yes
        '''DisplayOriginalMultiplayerMaps=Yes
        '''DisplayCounterstrikeMultiplayerMaps=Yes
        '''DisplayAftermathMultiplayerMaps=Yes
        '''UseSmallInfantry=No
        '''NoCD=Yes
        '''CounterstrikeEnabled=Yes
        '''AftermathEnabled=Yes
        '''For [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property redalert() As String
            Get
                Return ResourceManager.GetString("redalert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property skirmish() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("skirmish", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property soviet() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("soviet", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property title() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("title", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property ts() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ts", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 @echo off
        '''echo 正在更新...
        '''ping -n 2 127.0.0.1&gt;nul
        '''for /r %%F in (*.exe) do if %%~zF LSS 1 echo del &quot;%%F&quot;&gt;&gt;df.bat
        '''ping -n 1 127.0.0.1&gt;nul
        '''call df.bat
        '''ping -n 1 127.0.0.1&gt;nul
        '''del df.bat
        '''ping -n 1 127.0.0.1&gt;nul
        '''up_data.exe 2&gt;nul
        '''ping -n 1 127.0.0.1&gt;nul
        '''up_data.part01.exe 2&gt;nul
        '''ping -n 1 127.0.0.1&gt;nul
        '''echo 更新完成
        '''ping -n 1 127.0.0.1&gt;nul
        '''start 西木经典游戏汉化纪念版.exe 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property up() As String
            Get
                Return ResourceManager.GetString("up", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property updated_公用() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("updated_公用", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property xtitle_1280() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("xtitle_1280", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property xtitle_1280x960() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("xtitle_1280x960", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property xtitle_1728() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("xtitle_1728", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property xtitle_1920() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("xtitle_1920", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property xtitle_864() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("xtitle_864", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property xtitle_960() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("xtitle_960", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
