'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WestWood_Classic.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property _93() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("93", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 [Options]
        '''HardwareFills=0
        '''VideoBackBuffer=1
        '''FreeScrolling=0
        '''AutoScroll=1
        '''SlowPalette=1
        '''ScoreVolume=112
        '''Volume=113
        '''ScrollRate=3
        '''GameSpeed=1
        '''Compatibility=0
        '''DeathAnnounce=No
        '''Socket=0
        '''DestNet=00.00.00.00
        '''SafeScrolling=Yes
        '''
        '''[Video]
        '''Width=1024
        '''Height=768
        '''Brightness=128
        '''Contrast=128
        '''Tint=128
        '''Color=128
        '''VerticalVideoStretch=i  ; [S]canlines, [D]uplicate, [I]nterpolate
        '''StretchAttract=Yes
        '''
        '''[Music]
        '''IsScoreShuffle=0
        '''IsScoreRepeat=0
        '''UseCreditsMusic=Yes
        '''RemixScores=Yes         ; Enable music [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property conquer() As String
            Get
                Return ResourceManager.GetString("conquer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 [ddraw]
        '''; width and height of the window, defaults to the size game requests
        '''Width=0
        '''Height=0
        '''; bits per pixel, possible values: 16, 24 and 32, 0 = auto
        '''bpp=0
        '''Windowed=True
        '''; show window borders in windowed mode
        '''border=True
        '''; use letter- or windowboxing to make a best fit (GDI only!)
        '''Boxing=False
        '''; real rendering rate, -1 = screen rate, 0 = unlimited, n = cap
        '''Maxfps=120
        '''; vertical synchronization, enable if you get tearing (OpenGL only)
        '''vsync=False
        '''; scaling filter, nearest = sharp, linear =  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ddraw() As String
            Get
                Return ResourceManager.GetString("ddraw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property htitle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("htitle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property title() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("title", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
