copy ".\frenchlanguagepack.MIX-5资料片\cs.mix" "..\WestWood_Classic\WestWood_Classic\Resources"
copy ".\germancensoredlanguagepack.MIX-3苏军任务\soviet.mix" "..\WestWood_Classic\WestWood_Classic\Resources"
copy ".\germanlanguagepack.mix-2-盟军任务\allied.mix" "..\WestWood_Classic\WestWood_Classic\Resources"
copy ".\germanuncensoredlanguagepack.MIX-4-遭遇战\skirmish.mix" "..\WestWood_Classic\WestWood_Classic\Resources"
copy ".\russianlanguagepack.MIX-7余生资料片苏军\skirmish.mix" "..\WestWood_Classic\WestWood_Classic\Resources"
copy ".\spanishlanguagepack.MIX-6余生资料片\am_allied.mix" "..\WestWood_Classic\WestWood_Classic\Resources"
