copy conquer.eng "D:\games\Red Alert\ra"
copy hires.mix "D:\games\Red Alert\ra"
copy local.mix "D:\games\Red Alert\ra"
copy tutorial.ini "D:\games\Red Alert\ra"
copy mission.ini "D:\games\Red Alert\ra"
"D:\games\Red Alert\ra\ra95.exe"
