copy conquer.eng "D:\games\WestWood_Classic\RA"
copy hires.mix "D:\games\WestWood_Classic\RA"
copy local.mix "D:\games\WestWood_Classic\RA"
copy tutorial.ini "D:\games\WestWood_Classic\RA"
copy mission.ini "D:\games\WestWood_Classic\RA"
"D:\games\WestWood_Classic\RA\ra95.exe"
