copy chg\lang_chg.mix "F:\projects\updatasys\WestWood_Classic\temp\CnC95"
copy chm\lang_chm.mix "F:\projects\updatasys\WestWood_Classic\temp\CnC95"
copy chn\lang_chn.mix "F:\projects\updatasys\WestWood_Classic\temp\CnC95"
copy chv\lang_chv.mix "F:\projects\updatasys\WestWood_Classic\temp\CnC95"
copy deseichi.mix "F:\projects\updatasys\WestWood_Classic\temp\CnC95"
copy snowichi.mix "F:\projects\updatasys\WestWood_Classic\temp\CnC95"
copy tempichi.mix "F:\projects\updatasys\WestWood_Classic\temp\CnC95"
copy wintichi.mix "F:\projects\updatasys\WestWood_Classic\temp\CnC95"