copy deseichi.mix "D:\games\CnC95"
copy snowichi.mix "D:\games\CnC95"
copy tempichi.mix "D:\games\CnC95"
copy wintichi.mix "D:\games\CnC95"
copy chg\lang_chg.mix "D:\games\CnC95"
copy chm\lang_chm.mix "D:\games\CnC95"
copy chn\lang_chn.mix "D:\games\CnC95"
copy chv\lang_chv.mix "D:\games\CnC95"
"D:\games\CnC95\ÃüÁîÓëÕ÷·ş¼ÍÄî°æ.exe"
