copy deseichi.mix "D:\games\WestWood_Classic\CnC95"
copy snowichi.mix "D:\games\WestWood_Classic\CnC95"
copy tempichi.mix "D:\games\WestWood_Classic\CnC95"
copy wintichi.mix "D:\games\WestWood_Classic\CnC95"
copy chg\lang_chg.mix "D:\games\WestWood_Classic\CnC95"
copy chm\lang_chm.mix "D:\games\WestWood_Classic\CnC95"
copy chn\lang_chn.mix "D:\games\WestWood_Classic\CnC95"
copy chv\lang_chv.mix "D:\games\WestWood_Classic\CnC95"
"D:\games\WestWood_Classic\cnc95\c&c95.exe"
